export type Resource = { label: string; url: string };

export type Lesson = {
  id: string;
  section: string;
  title: string;
  video: string;
  provider: string;
  level?: "core" | "bridge";
  focus: string[];
  pause: string;
  pitfall: string;
  practice: Resource[];
  solutions?: Resource[];
};

export type Unit = {
  id: number;
  title: string;
  kicker: string;
  description: string;
  prerequisites: string;
  coverage: string[];
  source: Resource;
  lessons: Lesson[];
  review: Resource[];
  readiness: string[];
};

const lourdesRoot = "https://lourdesmath.weebly.com";
const uploadRoot = lourdesRoot + "/uploads/5/9/7/7/5977474/";
const lourdesFile = (file: string) => uploadRoot + file;
const youtube = (id: string) => "https://www.youtube.com/watch?v=" + id;

const pages = {
  1: lourdesRoot + "/unit-1---transformation-of-functions.html",
  2: lourdesRoot + "/unit-2---rational-expressions.html",
  3: lourdesRoot + "/unit-3---quadratics-functions.html",
  4: lourdesRoot + "/unit-4---exponential-functions.html",
  5: lourdesRoot + "/unit-5---trigonometric-ratios.html",
  6: lourdesRoot + "/unit-6---graphing-sinusoidals.html",
  7: lourdesRoot + "/unit-7---sequences--series.html",
  8: lourdesRoot + "/unit-8---financial-mathematics.html",
} as const;

const sheet = (page: string, student: string, solution?: string, extra: Resource[] = []) => ({
  practice: [
    { label: "Student worksheet", url: lourdesFile(student) },
    ...extra,
    { label: "Unit resource bank", url: page },
  ],
  solutions: solution ? [{ label: "Answer key", url: lourdesFile(solution) }] : [],
});

export const units: Unit[] = [
  {
    id: 1,
    title: "Introduction to Functions",
    kicker: "THE LANGUAGE OF THE COURSE",
    description: "Relations, notation, domain and range, parent functions, transformations, and inverses. This is the vocabulary every later unit uses.",
    prerequisites: "Grade 10 algebra basics and reading points on a graph.",
    coverage: ["1.1 relations & functions", "1.2 notation", "1.3 domain/range", "1.4–1.8 transformations & inverses"],
    source: { label: "Lourdes MCR3U Unit 1 hub", url: pages[1] },
    lessons: [
      {
        id: "u1-l1",
        section: "1.1",
        title: "Relations and functions",
        video: "8ndTq9VM6KM",
        provider: "Ms Havrot",
        focus: ["Classify tables, mappings, ordered pairs, and graphs.", "Use the one-input/one-output rule and the vertical-line test to justify your decision."],
        pause: "Before each example is explained, classify it yourself and name the repeated input or vertical line that proves your answer.",
        pitfall: "Several inputs may share one output; one input cannot have two outputs.",
        ...sheet(pages[1], "mcr3u_whatisafunction.docx", "mcr3u_whasisafunction_soln.pdf"),
      },
      {
        id: "u1-l2",
        section: "1.2",
        title: "Function notation",
        video: "3_WTOAB4n-s",
        provider: "Ms Havrot",
        focus: ["Read f(x) as an output, not multiplication.", "Evaluate f(a), solve f(x)=k, and substitute expressions such as f(2-x)."],
        pause: "Pause every time an input is substituted. Write the parentheses before simplifying, then compare your line with the video.",
        pitfall: "f(2x) means the input is 2x. It is not 2f(x).",
        ...sheet(pages[1], "mcr3u_functionnotation.docx", "mcr3u_functionnotation_soln.pdf"),
      },
      {
        id: "u1-l3",
        section: "1.3",
        title: "Domain, range, and interval notation",
        video: "FLGpA8QFYBw",
        provider: "Ms Havrot",
        focus: ["Read endpoint inclusion from open and closed circles.", "Write domains and ranges in set, inequality, and interval notation, including restrictions."],
        pause: "Draw the number line before writing interval notation. Say out loud whether each endpoint is included.",
        pitfall: "Infinity always uses a parenthesis. It is never included as an endpoint.",
        ...sheet(pages[1], "mcr3u_domainandrange.docx", "mcr3u_domainandrange_soln.pdf"),
      },
      {
        id: "u1-l4",
        section: "1.4",
        title: "Parent functions and key features",
        video: "A2Xp6aaFYnw",
        provider: "Ms Havrot",
        focus: ["Recognise linear, quadratic, square-root, absolute-value, and reciprocal parents.", "Read intercepts, vertex, asymptotes, domain, range, and end behaviour from a graph."],
        pause: "Pause at each new parent. Sketch it from memory and label its domain, range, and one key point.",
        pitfall: "A parent function is the untransformed reference graph, not the whole family of graphs.",
        ...sheet(pages[1], "mcr3u_unitone_summary.docx"),
      },
      {
        id: "u1-l5",
        section: "1.5",
        title: "Inverse functions",
        video: "vfxoaiCaqk8",
        provider: "Ms Havrot",
        focus: ["Swap x and y, then solve for the inverse.", "Use the horizontal-line test and connect inverse graphs by reflection in y=x."],
        pause: "Find the inverse without the video first. Verify by composing f(f⁻¹(x)) and checking the reflected graph.",
        pitfall: "A relation can have an inverse relation without having an inverse function.",
        ...sheet(pages[1], "mcr3u_inverseofafunction.docx", "mcr3u_inverseofafunction_soln.pdf"),
      },
      {
        id: "u1-l6",
        section: "1.6",
        title: "Translations, reflections, stretches, and compressions",
        video: "dRIwgEtUYA0",
        provider: "Ms Havrot",
        focus: ["Describe vertical and horizontal changes to a parent.", "Explain why changes inside f(x) affect x in the opposite-looking direction."],
        pause: "Predict the move before the graph appears. Write the mapping rule beside your prediction.",
        pitfall: "The horizontal scale is the reciprocal of the inside factor.",
        ...sheet(pages[1], "mcr3u_transformationsoffunctions_part1.docx", "mcr3u_transformationoffunctions_part1_soln.pdf"),
      },
      {
        id: "u1-l7",
        section: "1.7",
        title: "Mapping rules",
        video: "Wkf24MjBC-U",
        provider: "Ms Havrot",
        focus: ["Move points with a mapping rule.", "Build a transformed table and connect it to the equation."],
        pause: "Stop after the original point table. Transform every point yourself before checking the mapping.",
        pitfall: "Horizontal stretch factors are reciprocals in a point mapping; check with two points.",
        ...sheet(pages[1], "mcr3u_transformationsoffunctions_part2.docx", "mcr3u_transformationoffunctions_part2_soln.pdf"),
      },
      {
        id: "u1-l8",
        section: "1.8",
        title: "Graphing combinations of transformations",
        video: "H-IdTIi7Xr8",
        provider: "Ms Havrot",
        focus: ["Apply transformations in a reliable order.", "Sketch a transformed graph from its parent, key points, and asymptotes."],
        pause: "Make a five-point sketch before watching the completed graph. Check the intercepts and asymptote afterward.",
        pitfall: "Changing the order of transformations can change the result; use the mapping rule when unsure.",
        ...sheet(pages[1], "mcr3u_transformationsoffunctions_part3.doc"),
      },
    ],
    review: [
      { label: "Unit review worksheet", url: lourdesFile("mcr3u_functionsreview.doc") },
      { label: "Review answer key", url: lourdesFile("mcr3u_functionsreview_soln.pdf") },
      { label: "Practice quiz (1.1–1.3)", url: lourdesFile("mcr3u_introtofunctions_quiz.docx") },
      { label: "Ontario curriculum (official)", url: "https://www.edu.gov.on.ca/eng/curriculum/secondary/math1112currb.pdf" },
    ],
    readiness: ["I can decide whether a relation is a function and justify it.", "I can evaluate and solve function-notation questions without confusing f(a) with af(x).", "I can state domain and range in interval notation, including restrictions.", "I can sketch a transformed parent and find an inverse when it exists."],
  },
  {
    id: 2,
    title: "Algebraic Expressions",
    kicker: "THE SYMBOLIC TOOLKIT",
    description: "Polynomial operations, factoring, rational expressions, and rational-function graphs. These are the algebra tools underneath quadratics and exponentials.",
    prerequisites: "Grade 10 factoring, distributive property, fractions, and exponent rules.",
    coverage: ["2.1–2.3 polynomial operations & factoring", "2.4 simplifying rational expressions", "2.5 rational-function graphs", "2.6–2.7 rational operations"],
    source: { label: "Lourdes MCR3U Unit 2 hub", url: pages[2] },
    lessons: [
      {
        id: "u2-l1",
        section: "2.1",
        title: "Adding and subtracting polynomials",
        video: "3EKx3zeC8OU",
        provider: "Ms Havrot",
        focus: ["Combine only like terms.", "Add and subtract polynomials by aligning degree and sign."],
        pause: "Rewrite subtraction as adding the opposite before combining. Check the highest degree and constant term.",
        pitfall: "x and x² are different terms even though both contain x.",
        practice: [{ label: "Ontario Unit 2 resource bank", url: pages[2] }],
        solutions: [],
      },
      {
        id: "u2-l2",
        section: "2.2",
        title: "Multiplying polynomials",
        video: "dGQ6a3jiLbI",
        provider: "Ms Havrot",
        focus: ["Distribute every term and collect like terms.", "Use FOIL as a special case of the distributive property."],
        pause: "Multiply term by term on paper before watching the combination step.",
        pitfall: "Middle terms can cancel; do not drop them before you combine.",
        practice: [{ label: "Ontario Unit 2 resource bank", url: pages[2] }],
        solutions: [],
      },
      {
        id: "u2-l3",
        section: "2.3",
        title: "Factoring: common factors and grouping",
        video: "a9zVcmKx-Lc",
        provider: "Ms Havrot",
        focus: ["Reverse polynomial multiplication using common factors, grouping, and special products.", "Multiply back to verify every factorisation."],
        pause: "Factor the expression yourself, then multiply your factors back before watching the final check.",
        pitfall: "A factorisation is not finished if a common factor remains inside a bracket.",
        ...sheet(pages[2], "mcr3u_factoringreview_part1.docx", "mcr3u_factoringreview_part1_soln.pdf"),
      },
      {
        id: "u2-l4",
        section: "2.3",
        title: "Factoring simple trinomials",
        video: "a_B_Fbck5l8",
        provider: "Ms Havrot",
        focus: ["Factor x²+bx+c by finding a product and sum pair.", "Use signs and a multiplication check to catch errors."],
        pause: "Write the two numbers that multiply to c and add to b before splitting the trinomial.",
        pitfall: "The signs in the factors must produce both the middle term and the constant.",
        ...sheet(pages[2], "mcr3u_factoringreview_part2.docx", "mcr3u_factoringreview_part2_soln.pdf"),
      },
      {
        id: "u2-l5",
        section: "2.3",
        title: "Difference of squares and perfect-square trinomials",
        video: "NVo_jE2LawY",
        provider: "Ms Havrot",
        focus: ["Recognise difference-of-squares and perfect-square patterns.", "Multiply back to verify the signs and middle term."],
        pause: "Test a special-product pattern before using a longer method, then multiply back.",
        pitfall: "A difference of squares has two terms; a sum of squares does not factor over the real numbers.",
        ...sheet(pages[2], "mcr3u_factoringreview_part2.docx", "mcr3u_factoringreview_part2_soln.pdf"),
      },
      {
        id: "u2-l6",
        section: "2.3",
        title: "Complex trinomials",
        video: "ZyVwwCxDxt0",
        provider: "Ms Havrot",
        focus: ["Factor ax²+bx+c when the leading coefficient is not 1.", "Use a product–sum pair and grouping, then multiply back to verify."],
        pause: "Write the product a·c and the target middle coefficient before splitting the middle term.",
        pitfall: "The two numbers must multiply to ac and add to b; checking only one condition is not enough.",
        ...sheet(pages[2], "mcr3u_factoringreview_part2.docx", "mcr3u_factoringreview_part2_soln.pdf"),
      },
      {
        id: "u2-l7",
        section: "2.4",
        title: "Simplifying rational expressions and restrictions",
        video: "V-HXjfE2SOg",
        provider: "Ms Havrot",
        focus: ["Factor before cancelling.", "State restrictions from the original denominators and keep them with the simplified expression."],
        pause: "Write restrictions first. Then factor every numerator and denominator before cancelling.",
        pitfall: "Cancelling across addition is invalid: (x+2)/x cannot cancel x.",
        ...sheet(pages[2], "mcr3u_simplyfyingrationals.docx", "mcr3u_simplifyingrationals_soln.pdf"),
      },
      {
        id: "u2-l8",
        section: "2.5",
        title: "Graphs of rational functions",
        video: "HG1CBlGMFuc",
        provider: "Ms Havrot",
        focus: ["Find holes, intercepts, vertical asymptotes, and end behaviour from a rational rule.", "Connect restrictions and cancelled factors to the graph."],
        pause: "Factor and state restrictions before sketching. Mark the hole separately from an asymptote.",
        pitfall: "A hole is a missing point; a vertical asymptote is a boundary the graph approaches.",
        ...sheet(pages[2], "mcr3u_rationalexpressions_applicationpractice.docx", "mcr3u_rationalexpressions_applicationpractice_soln.pdf"),
      },
      {
        id: "u2-l9",
        section: "2.6",
        title: "Multiplying and dividing rational expressions",
        video: "Znsdg2NXOfQ",
        provider: "Ms Havrot",
        focus: ["Factor numerators and denominators before multiplying.", "Rewrite division as multiplication by a reciprocal and carry forward every restriction."],
        pause: "List restrictions, factor, then cancel. Do not multiply large polynomials before looking for factors.",
        pitfall: "A cancelled factor still creates a restriction because it was in the original denominator.",
        ...sheet(pages[2], "mcr3u_multiplyingdividingrationals.docx", "mcr3u_multiplyingdividingrationals_soln.pdf"),
      },
      {
        id: "u2-l10",
        section: "2.7",
        title: "Adding and subtracting rational expressions",
        video: "TGdEY0DPmnI",
        provider: "Ms Havrot",
        focus: ["Find the least common denominator.", "Combine numerators, factor, simplify, and state restrictions."],
        pause: "Build the LCD yourself and rewrite each numerator before watching the combine step.",
        pitfall: "The LCD is a common multiple of the entire denominators, not just their visible constants.",
        ...sheet(pages[2], "mcr3u_addingsubtractingrationals.docx", "mcr3u_addingsubtractingrationals_soln.pdf"),
      },
    ],
    review: [
      { label: "Unit summary", url: lourdesFile("mcr3u_rationalssummary.doc") },
      { label: "Unit quiz", url: lourdesFile("mcr3u_rationalexpressionsquiz.pdf") },
      { label: "Quiz answer key", url: lourdesFile("mcr3u_rationalexpressionsquizsoln.pdf") },
      { label: "Lourdes worksheet bank", url: pages[2] },
    ],
    readiness: ["I can add, subtract, multiply, and divide polynomials while showing the algebra.", "I can factor and verify by multiplication.", "I can simplify rational expressions and state every excluded value.", "I can add rational expressions using an LCD without losing restrictions."],
  },
  {
    id: 3,
    title: "Quadratic Functions",
    kicker: "THE PARABOLA UNIT",
    description: "The full Grade 11 quadratic sequence: properties, max/min, completing the square, inverse quadratics, radicals, equations, zeros, families, and linear–quadratic systems.",
    prerequisites: "Unit 2 factoring and completing the square, plus graphing from Unit 1.",
    coverage: ["3.1 properties", "3.2 max/min & completing the square", "3.3 inverse quadratics", "3.4 radicals", "3.5–3.8 equations, zeros, families & systems"],
    source: { label: "Lourdes MCR3U Unit 3 hub", url: pages[3] },
    lessons: [
      {
        id: "u3-l1",
        section: "3.1",
        title: "Properties and forms of quadratic functions",
        video: "Q3kKI4ZfSIU",
        provider: "Passionate Minds",
        focus: ["Identify opening direction, axis of symmetry, vertex, intercepts, domain, and range.", "Choose standard, vertex, or factored form for the feature the question asks for."],
        pause: "Given each form, predict which features are immediate before the video translates it.",
        pitfall: "The axis of symmetry passes through the vertex; it is not the y-coordinate of the vertex.",
        ...sheet(pages[3], "mcr3u_propertiesofquadraticfunctions.docx", "mcr3u_propertiesofquadraticfunctions_soln.pdf"),
      },
      {
        id: "u3-l2",
        section: "3.2",
        title: "Maximum and minimum values",
        video: "aRhZ3fRwWBU",
        provider: "Passionate Minds",
        focus: ["Find the vertex and interpret its y-value as a maximum or minimum.", "Model and explain max/min situations with units and a sensible domain."],
        pause: "State the vertex, opening, and range from each equation before graphing.",
        pitfall: "The vertex is a point; the maximum or minimum is its y-value.",
        ...sheet(pages[3], "mcr3u_maxminvaluesofquadratics.docx", "mcr3u_maxminvaluesofquadratics_soln.pdf"),
      },
      {
        id: "u3-l3",
        section: "3.2",
        title: "Completing the square",
        video: "7m3J7vmmD3o",
        provider: "Ms Havrot",
        focus: ["Convert standard form to vertex form.", "Use completing the square to expose the vertex and solve when factoring is awkward."],
        pause: "Add and subtract the needed constant yourself, remembering that the balance must stay equal.",
        pitfall: "When the x coefficient is not 1, factor it before completing the square.",
        ...sheet(pages[3], "mcr3u_maxminvaluesofquadratics.docx", "mcr3u_maxminvaluesofquadratics_soln.pdf"),
      },
      {
        id: "u3-l4",
        section: "3.3",
        title: "The inverse of a quadratic function",
        video: "GEHFIzcQr-E",
        provider: "Passionate Minds",
        focus: ["Restrict a quadratic domain so its inverse is a function.", "Swap x and y, solve, and connect the inverse graph to y=x."],
        pause: "Choose and state the restricted domain before solving for the inverse.",
        pitfall: "A full parabola fails the horizontal-line test; the restriction is part of the inverse function.",
        ...sheet(pages[3], "mcr3u_inverseofaquadratic.docx", "mcr3u_inverseofaquadratic_soln.pdf"),
      },
      {
        id: "u3-l5",
        section: "3.4",
        title: "Operations with radicals",
        video: "dKHY4EwATV4",
        provider: "Passionate Minds",
        focus: ["Simplify radicals by extracting perfect-square factors.", "Add, subtract, multiply, and divide radicals when the operation is defined."],
        pause: "Simplify every radicand before deciding whether terms are like.",
        pitfall: "√(a+b) does not equal √a+√b.",
        ...sheet(pages[3], "mcr3u_operationswithradicals.docx", "mcr3u_operationswithradicals_soln.pdf"),
      },
      {
        id: "u3-l6",
        section: "3.5",
        title: "Solving quadratic equations",
        video: "ibuUziAnnaI",
        provider: "Passionate Minds",
        focus: ["Choose factoring, completing the square, or the quadratic formula deliberately.", "Verify roots in the original equation and reject extraneous values from a context."],
        pause: "Set the equation equal to zero and choose a method before watching the worked solution.",
        pitfall: "The zero-product property only applies after one side is zero.",
        ...sheet(pages[3], "mcr3u_solvingquadraticequations.docx", "mcr3u_solvingquadraticequations_soln.pdf"),
      },
      {
        id: "u3-l7",
        section: "3.6",
        title: "Zeros and the discriminant",
        video: "21xO_win0lo",
        provider: "Passionate Minds",
        focus: ["Connect zeros, x-intercepts, factors, and solutions.", "Use b²−4ac to classify two, one, or zero real zeros before solving."],
        pause: "Calculate or predict the discriminant before you solve. Explain what the sign means on the graph.",
        pitfall: "A negative discriminant means no real x-intercepts, not that the algebraic expression is meaningless.",
        ...sheet(pages[3], "mcr3u_solvingquadraticequations.docx", "mcr3u_solvingquadraticequations_soln.pdf"),
      },
      {
        id: "u3-l8",
        section: "3.7",
        title: "Families of quadratic functions",
        video: "OKWI2FopJ4Q",
        provider: "Passionate Minds",
        focus: ["Describe how a parameter changes a family of parabolas.", "Use a shared feature such as a vertex, root, or y-intercept to determine a rule."],
        pause: "Predict which parameter controls the feature before comparing the family graphs.",
        pitfall: "A family parameter can change more than one visible feature; test with an equation, not only a sketch.",
        ...sheet(pages[3], "mcr3u_familyofquadraticfunctions.docx", "mcr3u_familyofquadraticfunctions_soln.pdf"),
      },
      {
        id: "u3-l9",
        section: "3.8",
        title: "Linear–quadratic systems",
        video: "1QuXn3hoRAU",
        provider: "Ms Havrot",
        focus: ["Solve line–parabola intersections by substitution.", "Interpret zero, one, or two intersection points in a graph and in a context."],
        pause: "Substitute and solve the quadratic before looking at the graph. Then match each root to its y-coordinate.",
        pitfall: "A root gives an x-coordinate; use either original equation to find the corresponding y.",
        ...sheet(pages[3], "mcr3u_intersectionoflinesandparabolas.docx", "mcr3u_intersectionoflinesandparabolas_soln.pdf"),
      },
    ],
    review: [
      { label: "Quadratic review worksheet", url: lourdesFile("mcr3u_quadraticreview.doc") },
      { label: "Review answer key", url: lourdesFile("mcr3u_quadraticreviewsolutions.pdf") },
      { label: "Quadratic application practice", url: lourdesFile("mcr3u_quadraticapplicationreview.pdf") },
      { label: "Lourdes lesson bank", url: pages[3] },
    ],
    readiness: ["I can choose a useful quadratic form and read its key features.", "I can determine a maximum or minimum and explain it in context.", "I can solve by factoring, completing the square, or the quadratic formula and justify the choice.", "I can use the discriminant, inverse restrictions, families, and linear–quadratic systems correctly."],
  },
  {
    id: 4,
    title: "Exponential Functions",
    kicker: "GROWTH, DECAY, AND CHANGE",
    description: "Build, transform, solve, and interpret exponential models, including growth/decay, half-life, and doubling time.",
    prerequisites: "Exponent laws and transformations from Units 1–2.",
    coverage: ["4.1 exponent laws", "4.2 rational exponents", "4.3 simplifying expressions", "4.4–4.6 transformations & equations", "4.7 applications"],
    source: { label: "Lourdes MCR3U Unit 4 hub", url: pages[4] },
    lessons: [
      {
        id: "u4-l1",
        section: "4.1",
        title: "Review of exponent laws",
        video: "uyMeyWA-Fcg",
        provider: "Peter Jones",
        focus: ["Use product, quotient, power, zero, and negative-exponent laws.", "Rewrite an expression in a form that reveals its base and growth factor."],
        pause: "Predict the exponent before the video simplifies. Write the law beside every step.",
        pitfall: "A power distributes over multiplication, not addition: (a+b)ⁿ is not aⁿ+bⁿ.",
        ...sheet(pages[4], "mcr3u_introtoexponents.docx", "mcr3u_introtoexponents_soln.pdf"),
      },
      {
        id: "u4-l2",
        section: "4.2",
        title: "Rational exponents",
        video: "p2rubTxuzOc",
        provider: "Peter Jones",
        focus: ["Translate between radicals and rational exponents.", "Simplify expressions while respecting powers, roots, and restrictions."],
        pause: "Rewrite each rational exponent as a root before checking the worked simplification.",
        pitfall: "The denominator of a rational exponent is the root; the numerator is the power.",
        ...sheet(pages[4], "mcr3u_rationalexponents.docx", "mcr3u_rationalexponents_soln.pdf"),
      },
      {
        id: "u4-l3",
        section: "4.3",
        title: "Simplifying exponential expressions",
        video: "QivMTcC-pCQ",
        provider: "Peter Jones",
        focus: ["Combine exponent laws in multi-step expressions.", "Keep coefficients, bases, and exponents separate while simplifying."],
        pause: "Name the single exponent law you will use next before watching the line.",
        pitfall: "Only like bases combine through exponent laws; different bases cannot be merged by adding exponents.",
        ...sheet(pages[4], "mcr3u_simplifyingexponentialexpressions.docx", "mcr3u_simplifyingrationalexpressions_soln.pdf"),
      },
      {
        id: "u4-l4",
        section: "4.4",
        title: "Transformations of exponentials: part 1",
        video: "CdfoSvTepnE",
        provider: "Peter Jones",
        focus: ["Read y=a·bˣ+c and identify vertical stretch, reflection, and translation.", "Use a table or parent graph to check a transformed model."],
        pause: "List the parent, scale, reflection, and vertical shift before plotting.",
        pitfall: "The horizontal asymptote is y=c, not automatically y=0.",
        ...sheet(pages[4], "mcr3u_transformationsofexponentials_part1.docx", "mcr3u_transformationsofexponentials_part1_soln.pdf"),
      },
      {
        id: "u4-l5",
        section: "4.5",
        title: "Transformations of exponentials: part 2",
        video: "yBmLYKiAa3A",
        provider: "Peter Jones",
        focus: ["Handle inside changes and horizontal stretches/compressions.", "Connect each parameter in y=a·bᵏ⁽ˣ⁻ᵈ⁾+c to the graph."],
        pause: "Make a five-point sketch using the parent before checking the transformed graph.",
        pitfall: "The horizontal scale is 1/|k|, not |k|.",
        ...sheet(pages[4], "mcr3u_transformationsofexponentials_part2.docx", "mcr3u_transformationsofexponentials_part2_soln.pdf"),
      },
      {
        id: "u4-l6",
        section: "4.6",
        title: "Solving exponential equations and tables",
        video: "90jaeyJDf_Y",
        provider: "Peter Jones",
        focus: ["Match bases when possible and use a table or graph to verify.", "Explain why a solution is exact or an approximation."],
        pause: "Try rewriting both sides with the same base before using a calculator.",
        pitfall: "Do not equate exponents until the bases are truly equal and valid.",
        ...sheet(pages[4], "mcr3u_solvingexponentialequationsandtableofvalues.docx", "mcr3u_solvingexponentialequationsandtableofvalues_soln.pdf"),
      },
      {
        id: "u4-l7",
        section: "4.7",
        title: "Growth and decay applications",
        video: "yDO-9H9C_ns",
        provider: "Peter Jones",
        focus: ["Build a model from an initial value and percent change.", "Interpret every variable with units and check the scale of the answer."],
        pause: "Write what t=0 means and convert every percent to a multiplier before solving.",
        pitfall: "A 6% increase uses 1.06, while a 6% decrease uses 0.94.",
        ...sheet(pages[4], "mcr3u_applicationsofexponentials_part1.docx", "mcr3u_applicationsofexponentials_part1_soln.pdf"),
      },
      {
        id: "u4-l8",
        section: "4.7",
        title: "Half-life and doubling time",
        video: "NfFFCLwLRHs",
        provider: "Peter Jones",
        focus: ["Use a model to solve for time, amount, half-life, or doubling time.", "Report an answer with a sensible unit and interpretation."],
        pause: "Estimate whether the answer should be a short or long time before calculating.",
        pitfall: "Half-life is the time for the amount to halve; it is not half of the decay factor.",
        ...sheet(pages[4], "mcr3u_applicationsofexponentials_part2.docx", "mcr3u_applicationsofexponentials_part2_soln.pdf"),
      },
    ],
    review: [
      { label: "Exponential review worksheet", url: lourdesFile("mcr3u_exponentials_review_worksheet.docx") },
      { label: "Review answer key", url: lourdesFile("mcr3u_exponentials_review_worksheet_soln.pdf") },
      { label: "Unit summary", url: lourdesFile("mcr3u_exponentials_unitsummary.docx") },
      { label: "Lourdes lesson bank", url: pages[4] },
    ],
    readiness: ["I can simplify exponent expressions and translate rational exponents.", "I can build and transform an exponential model from a table or context.", "I can solve exponential equations and verify the result.", "I can explain growth, decay, half-life, doubling time, and units in context."],
  },
  {
    id: 5,
    title: "Trigonometric Ratios",
    kicker: "TRIG GEOMETRY",
    description: "Acute and special angles, all-quadrant ratios, reciprocal ratios, identities, the sine/cosine laws, ambiguous cases, and 3D problems.",
    prerequisites: "Right-triangle vocabulary, Pythagorean theorem, and a scientific calculator in degree mode.",
    coverage: ["5.1 acute ratios", "5.2 special angles", "5.3–5.4 Cartesian grid & CAST", "5.5 identities", "5.6–5.8 laws, ambiguous case & 3D"],
    source: { label: "Lourdes MCR3U Unit 5 hub", url: pages[5] },
    lessons: [
      {
        id: "u5-l1",
        section: "5.1",
        title: "Acute ratios and reciprocals",
        video: "VQxCSJHPXQI",
        provider: "Peter Jones",
        focus: ["Choose sine, cosine, or tangent from a labelled right triangle.", "Use secant, cosecant, and cotangent as reciprocal ratios."],
        pause: "Label opposite, adjacent, and hypotenuse before touching the calculator.",
        pitfall: "The side names depend on the chosen angle; opposite and adjacent can switch.",
        ...sheet(pages[5], "mcr3u_trigratiosofacuteangles_and_trigreciprocals.docx", "mcr3u_trigratiosofacuteangles_and_trigreciprocals_soln.pdf"),
      },
      {
        id: "u5-l2",
        section: "5.2",
        title: "Special triangles and exact values",
        video: "Y8kCay3lOU4",
        provider: "Peter Jones",
        focus: ["Build 30–60–90 and 45–45–90 triangles.", "Use exact values instead of decimal approximations."],
        pause: "Derive the ratios before memorising them, then test 30°, 45°, and 60°.",
        pitfall: "Exact-value questions need fractions and radicals, not rounded decimals.",
        ...sheet(pages[5], "mcr3u_specialtriangles_and_exactvalues.docx", "mcr3u_specialtriangles_and_exactvalues_soln.pdf"),
      },
      {
        id: "u5-l3",
        section: "5.3",
        title: "Trig ratios on the Cartesian grid",
        video: "m_WZUzHFpWA",
        provider: "Peter Jones",
        focus: ["Place an angle in standard position.", "Use a point on the terminal arm to find all three ratios and the reference angle."],
        pause: "Draw the terminal arm and label x, y, and r before calculating.",
        pitfall: "The radius r is positive; the signs come from x and y.",
        ...sheet(pages[5], "mcr3u_trigonometryandthecartesiangrid.docx", "mcr3u_trigonometryandthecartesiangrid_soln.pdf"),
      },
      {
        id: "u5-l4",
        section: "5.4",
        title: "The CAST rule and angles from 0° to 360°",
        video: "z-1kohZtMsU",
        provider: "Peter Jones",
        focus: ["Use the quadrant sign pattern to evaluate exact and approximate ratios.", "Find every angle in a specified interval."],
        pause: "Draw the quadrant and reference angle before using the calculator.",
        pitfall: "Inverse trig returns a principal angle; it is not the complete answer on 0°–360°.",
        ...sheet(pages[5], "mcr3u_thecastrule.docx", "mcr3u_thecastrule_soln.pdf"),
      },
      {
        id: "u5-l5",
        section: "5.5",
        title: "Proving trigonometric identities: part 1",
        video: "iAZPw9iN60s",
        provider: "Peter Jones",
        focus: ["Use reciprocal, quotient, and Pythagorean identities.", "Change one side at a time until it matches the other side."],
        pause: "Choose the more complicated side and name the identity that moves it toward the other.",
        pitfall: "Checking one angle is not a proof of an identity.",
        ...sheet(pages[5], "mcr3u_provingidentities_part1.docx", "mcr3u_provingidentities_part1_soln.pdf"),
      },
      {
        id: "u5-l6",
        section: "5.5",
        title: "Proving trigonometric identities: part 2",
        video: "8NrXNFRkgFc",
        provider: "Peter Jones",
        focus: ["Simplify complex identity proofs without changing both sides at once.", "Recognise when factoring or a common denominator is the next useful move."],
        pause: "Write the target form and one legal algebraic move before watching.",
        pitfall: "Never divide by an expression without considering where it could be zero.",
        ...sheet(pages[5], "mcr3u_provingidentities_part2.docx", "mcr3u_provingidentities_part2_soln.pdf"),
      },
      {
        id: "u5-l7",
        section: "5.6–5.7",
        title: "Sine law, cosine law, and the ambiguous case",
        video: "_iwmJLabjqk",
        provider: "Peter Jones",
        focus: ["Choose sine law or cosine law from the information given.", "Detect zero, one, or two possible triangles and report only valid solutions."],
        pause: "Name the known side–angle pair and sketch the diagram before choosing a law.",
        pitfall: "The largest side is opposite the largest angle; use this check to catch a wrong diagram.",
        ...sheet(pages[5], "mcr3u_sinelawcosinelaw_and_ambiguouscase.docx", "mcr3u_sinelawcosinelaw_and_ambiguouscase_soln.pdf"),
      },
      {
        id: "u5-l8",
        section: "5.8",
        title: "Three-dimensional trigonometry",
        video: "NHrng7rSm2c",
        provider: "Peter Jones",
        focus: ["Split a 3D diagram into useful right triangles.", "Use a clear auxiliary line and keep the requested angle or distance attached to the diagram."],
        pause: "Draw the hidden right triangle before calculating any ratio.",
        pitfall: "A 3D diagonal is not automatically a side of the visible face triangle.",
        ...sheet(pages[5], "mcr3u_threedimensionalproblems.docx"),
      },
    ],
    review: [
      { label: "Trigonometry review worksheet", url: lourdesFile("mcr3u_trigonometricfunctions_reviewworksheet.docx") },
      { label: "Review answer key", url: lourdesFile("mcr3u_trigonometricfunctions_reviewworksheet_soln.pdf") },
      { label: "Unit quiz", url: lourdesFile("mcr3u_trigonometryquiz.doc") },
      { label: "Lourdes lesson bank", url: pages[5] },
    ],
    readiness: ["I can give exact special-angle values and use degree mode correctly.", "I can solve every trig equation on 0°–360° with all valid answers.", "I can select and apply a triangle law from a labelled diagram.", "I can explain an ambiguous case, prove a basic identity, and solve a 3D problem."],
  },
  {
    id: 6,
    title: "Sinusoidal Functions",
    kicker: "MODELLING PERIODIC CHANGE",
    description: "Read periodic behaviour, graph sine and cosine, reverse-engineer equations, and model real cycles with amplitude, period, phase shift, and midline.",
    prerequisites: "Unit 5 trig ratios, transformations from Unit 1, and a graphing calculator or Desmos.",
    coverage: ["6.1 periodic behaviour", "6.2 sine & cosine curves", "6.3 key features", "6.4–6.5 transformations & graphing", "6.6–6.7 models and solving"],
    source: { label: "Lourdes MCR3U Unit 6 hub", url: pages[6] },
    lessons: [
      {
        id: "u6-l1",
        section: "6.1",
        title: "Modelling periodic behaviour",
        video: "n-IpGWIAPII",
        provider: "Peter Jones",
        focus: ["Identify cycle, period, amplitude, and midline from a context.", "Connect repeated data to a sinusoidal graph."],
        pause: "Describe one full cycle in words before looking at the equation.",
        pitfall: "The period is one complete cycle, not the distance from a maximum to a minimum.",
        ...sheet(pages[6], "mcr3u_modelingperiodicbehaviour.docx", "mcr3u_modelingperiodicbehaviour_soln.pdf"),
      },
      {
        id: "u6-l2",
        section: "6.2",
        title: "The sine and cosine curves",
        video: "PNV_qIRpQu0",
        provider: "Peter Jones",
        focus: ["Use five key points over one cycle.", "Compare sine and cosine starting positions and signs."],
        pause: "Mark the quarter-period points before connecting the curve.",
        pitfall: "Amplitude is a distance from the midline, so it is always nonnegative.",
        ...sheet(pages[6], "mcr3u_introductiontothesineandcosinecurve.docx", "mcr3u_introductiontothesineandcosinecurve_soln.pdf"),
      },
      {
        id: "u6-l3",
        section: "6.3",
        title: "Reading features of periodic functions",
        video: "xDSoGT-PESk",
        provider: "Ms Havrot",
        focus: ["Read amplitude, period, maximum, minimum, and midline from a graph.", "Explain what each feature means in a real situation."],
        pause: "Label one cycle and the midline yourself before checking the interpretation.",
        pitfall: "The midline is the average of the maximum and minimum, not the minimum.",
        ...sheet(pages[6], "mcr3u_sinusoidalfunctionssummary.docx"),
      },
      {
        id: "u6-l4",
        section: "6.4",
        title: "Transformations of sinusoidals: part 1",
        video: "3TwbyYU-9uQ",
        provider: "Peter Jones",
        focus: ["Read a, k, d, and c from y=a sin(k(x-d))+c.", "Connect amplitude, period, phase shift, and midline to graph changes."],
        pause: "Fill in the four parameters before plotting any points.",
        pitfall: "In degree mode, period is 360°/|k|; it is not 360°|k|.",
        ...sheet(pages[6], "mcr3u_transformationsofsinusoidalspart1.docx", "mcr3u_transformationsofsinusoidalspart1_soln.pdf"),
      },
      {
        id: "u6-l5",
        section: "6.5",
        title: "Transformations of sinusoidals: part 2",
        video: "mu4CFULWzUo",
        provider: "Peter Jones",
        focus: ["Sketch a transformed sine or cosine graph accurately.", "Use a table of five key points to check reflections and phase shifts."],
        pause: "Choose sine or cosine and plot the first cycle before watching the finished sketch.",
        pitfall: "A negative a reflects across the midline; it does not make amplitude negative.",
        ...sheet(pages[6], "mcr3u_transformationsofsinusoidalspart2.docx", "mcr3u_transformationsofsinusoidalspart2_soln.pdf"),
      },
      {
        id: "u6-l6",
        section: "6.6",
        title: "Finding an equation from a graph",
        video: "cpHiZ-8mxmc",
        provider: "Ms Havrot",
        focus: ["Find midline and amplitude from extrema.", "Use a maximum or minimum to choose a convenient sine/cosine phase shift and verify a key point."],
        pause: "Read the four parameters from the graph before checking the equation.",
        pitfall: "A graph can have many equivalent equations; verify with a key point and the period.",
        ...sheet(pages[6], "mcr3u_sinusoidalfunctionsworksheet.docx", "mcr3u_sinusoidalfunctionsworksheet_soln.pdf"),
      },
      {
        id: "u6-l7",
        section: "6.7",
        title: "Sinusoidal applications and solving",
        video: "G04daK3Yy0Q",
        provider: "Peter Jones",
        focus: ["Build a model from data or a graph.", "Solve for times when a target value is reached and report every answer in the requested interval."],
        pause: "Sketch the cycle and mark the target line before solving.",
        pitfall: "A target height may occur twice in a cycle; report every valid time.",
        ...sheet(pages[6], "mcr3u_applicationsofsinusoidalfunctions.docx", "mcr3u_applicationsofsinusoidalfunctions_soln.pdf"),
      },
    ],
    review: [
      { label: "Sinusoidal review worksheet", url: lourdesFile("mcr3u_sinusoidalfunctionsworksheet.docx") },
      { label: "Review answer key", url: lourdesFile("mcr3u_sinusoidalfunctionsworksheet_soln.pdf") },
      { label: "Unit summary", url: lourdesFile("mcr3u_sinusoidalfunctionssummary.docx") },
      { label: "Lourdes lesson bank", url: pages[6] },
    ],
    readiness: ["I can read amplitude, period, midline, and phase shift from a graph or equation.", "I can draw one accurate cycle with labelled key points.", "I can create a sinusoidal model from a context and explain every parameter.", "I can solve a target-value question and include all times in the required interval."],
  },
  {
    id: 7,
    title: "Discrete Functions",
    kicker: "SEQUENCES, SERIES, AND PATTERNS",
    description: "Arithmetic and geometric sequences, series, recursion, and the binomial theorem. Financial mathematics is kept as an optional Nelson extension because it is not one of the seven units in your welcome slides.",
    prerequisites: "Exponent laws, algebraic rearranging, and comfort with a scientific calculator.",
    coverage: ["7.1 arithmetic sequences", "7.2 geometric sequences", "7.3–7.4 rules & recursion", "7.5–7.6 series", "7.7 binomial theorem"],
    source: { label: "Lourdes MCR3U Unit 7 hub", url: pages[7] },
    lessons: [
      {
        id: "u7-l1",
        section: "7.1",
        title: "Arithmetic sequences",
        video: "4GR-O32W6dc",
        provider: "Peter Jones",
        focus: ["Find a common difference and the explicit rule.", "Use aₙ=a₁+(n−1)d and explain what n represents."],
        pause: "Classify the pattern and write the recursive rule before using the explicit formula.",
        pitfall: "A common difference adds; a common ratio multiplies. Do not swap d and r.",
        ...sheet(pages[7], "mcr3u_arithmeticsequences.docx", "mcr3u_arithmeticsequences_soln.pdf"),
      },
      {
        id: "u7-l2",
        section: "7.2",
        title: "Geometric sequences",
        video: "kkrhzVXko8g",
        provider: "Peter Jones",
        focus: ["Find a common ratio and the explicit rule.", "Use aₙ=a₁rⁿ⁻¹ and interpret growth or decay in a discrete context."],
        pause: "Divide consecutive terms to find r before checking the formula.",
        pitfall: "A common ratio can be negative or fractional; it is still multiplication, not addition.",
        ...sheet(pages[7], "mcr3u_geometricsequences.docx", "mcr3u_geometricsequences_soln.pdf"),
      },
      {
        id: "u7-l3",
        section: "7.5",
        title: "Arithmetic series",
        video: "1TfHHTSS1jk",
        provider: "Ms Havrot",
        focus: ["Distinguish a sequence from its sum.", "Use Sₙ=n/2[2a₁+(n−1)d] and identify the first, last, and number of terms."],
        pause: "Write the first and last terms and count n before substituting.",
        pitfall: "The number of terms is not automatically the last term's value.",
        ...sheet(pages[7], "mcr3u_arithmeticseries.docx", "mcr3u_arithmeticseries_soln.pdf"),
      },
      {
        id: "u7-l4",
        section: "7.6",
        title: "Geometric series",
        video: "6nDHDFEknSM",
        provider: "Peter Jones",
        focus: ["Use finite geometric series formulas.", "Interpret a sum in a repeated-payment or pattern context."],
        pause: "Write a₁, r, and n beside the formula before calculating.",
        pitfall: "The finite formula requires the correct first term and number of terms; do not use the last term as n.",
        ...sheet(pages[7], "mcr3u_geometricseries.docx", "mcr3u_geometricseries_soln.pdf"),
      },
      {
        id: "u7-l5",
        section: "7.3–7.4",
        title: "Recursive definitions",
        video: "UYibLAPfIx4",
        provider: "Peter Jones",
        focus: ["Read an initial value and recurrence together.", "Generate terms and convert between recursive and explicit descriptions."],
        pause: "Generate the first five terms yourself, then compare each transition.",
        pitfall: "A recurrence without its initial value is incomplete.",
        ...sheet(pages[7], "mcr3u_recursion.docx", "mcr3u_recursion_soln.docx"),
      },
      {
        id: "u7-l6",
        section: "7.7",
        title: "The binomial theorem",
        video: "y9uANs16jbY",
        provider: "Peter Jones",
        focus: ["Use Pascal coefficients and binomial coefficients to expand powers.", "Check that the powers and coefficients match the exponent."],
        pause: "Build the coefficient row before expanding, then check the powers add to n.",
        pitfall: "The first Pascal row is usually numbered 0; match the row to the exponent.",
        ...sheet(pages[7], "mcr3u_binomialtheorem.docx", "mcr3u_binomialtheorem_soln.pdf"),
      },
    ],
    review: [
      { label: "Sequences and series practice", url: lourdesFile("mcr3u_sequencesseries_practiceworksheet.docx") },
      { label: "Practice answer key", url: lourdesFile("mcr3u_sequencesseries_practiceworksheet_soln.pdf") },
      { label: "Unit summary", url: lourdesFile("mcr3u_sequencesandseries_summary.docx") },
      { label: "Optional financial-math extension", url: pages[8] },
    ],
    readiness: ["I can classify a pattern as arithmetic, geometric, recursive, or neither.", "I can find a term or sum and explain what n means.", "I can move between a context, a recurrence, and an explicit formula.", "I can expand a binomial and justify the coefficients."],
  },
];

export { youtube };
